vhive-serverless/vHive

Makefile
bench_test.go
ctriface/go.mod
ctriface/go.sum
ctriface/iface.go
ctriface/manual_cleanup_test.go
fccd-orchestrator.go
functions.go
go.mod
go.sum
metrics/metrics.go

Signed-off-by: Plamen Petrov <plamb0brt@gmail.com>

Changes to support s3 workloads

---

.github/workflows/nightly_tests.yml

Fix nightly test schedule bug and update the trigger timing to 0000 UTC.
Signed-off-by: Shyam Jesalpura s.jesalpura@gmail.com

Update and fix nightly test schedule

---

README.md
docs/developers_guide.md
docs/quickstart_guide.md
examples/README.md

Extended the developer's guide on the modes of operation and performance analysis.

Developer's guide extended with performance analysis description

---

.github/workflows/build_docker_images.yml
function-images/lr_serving/Dockerfile
scripts/github_runner/Dockerfile.github_runner

Fix lr_serving and github runner docker image build.

---

.github/dependabot.yml

Enabled dependabot

---

README.md

Added info about our channel on Firecracker slack

---

docs/developers_guide.md

add [kind](https://kind.sigs.k8s.io/) to the list of dependencies

update developers guide to include [kind](https://kind.sigs.k8s.io/)

---

.github/dependabot.yml

Changed dependabot frequency to weekly

---

ctriface/Makefile
ctriface/bench_test.go
ctriface/failing_test.go
ctriface/iface.go
ctriface/iface_test.go
ctriface/manual_cleanup_test.go
ctriface/orch.go
ctriface/orch_options.go
misc/misc_test.go
misc/vm_pool.go
taps/tapManager.go
taps/taps_test.go
vhive.go
vhive_test.go

* Added a test for internet connectivity
* Set up nameservers when creating a VM
* Added functionality to configure iptables at the tap creation

Internet connectivity in MicroVMs

---

.github/workflows/integration_tests.yml
.github/workflows/nightly_tests.yml
.github/workflows/unit_tests.yml

fetch latest binaries before running CI tests

---

scripts/github_runner/clean_cri_runner.sh
scripts/github_runner/start_runners.sh

- Fixes one of the issues mentioned in #121
- Fix CRI runner name collision
- Add restart runner functionality

Cleaning script fix: remove all folders created by fc-ctrd

---

.github/workflows/cri_minio_test.yml
.github/workflows/cri_test.yml

Upload CRI-test logs as artifacts
Signed-off-by: shyam Jesal <s.jesalpura@gmail.com>

Upload model artifacts to github

---

configs/.wordlist.txt
docs/quickstart_guide.md

The profile's name and hyperlink are up to date in the quickstart guide.
Fixes #242 

Updated to the recommended Cloudlab profile

---

function-images/docker_build.sh
function-images/minio_scripts/create_minio_bucket.sh
function-images/minio_scripts/install_minio.sh
function-images/minio_scripts/put_in_bucket.sh
function-images/minio_scripts/start_minio_server.sh
scripts/github_runner/clean_cri_runner.sh
scripts/github_runner/setup_cri_dev_env.sh
scripts/github_runner/setup_runner_cri.sh
scripts/github_runner/setup_runner_host.sh
scripts/github_runner/start_runners.sh
scripts/setup_zipkin.sh

Move shebang lines of all scripts to the first line

---

README.md
configs/.wordlist.txt
docs/contributing_to_vhive.md

Adds a page with guidelines on contributing to vHive.

Contributing to vHive document

---

.github/workflows/image_build.yml
configs/golang/Dockerfile

Adds workflow for vhiveease/golang deployment and a dockerfile in the configs folder

Adds vhiveease/golang workflow

---

configs/commitlint.config.js

fix commitlinter to fail on unsigned commit

---

README.md

Added twitter badge

---

configs/.wordlist.txt
docs/contributing_to_vhive.md

add instructions to use private Go modules

---

CHANGELOG.md
examples/knative-eventing-tutorial/go.mod
examples/protobuf/helloworld/go.mod
function-images/tests/save_load_minio/Dockerfile
function-images/tests/save_load_minio/client/go.mod
function-images/tests/save_load_minio/proto_gen/go.mod
function-images/tests/save_load_minio/server/go.mod
go.mod
scripts/install_go.sh

Bump Go to v1.16.4

---

docs/developers_guide.md

rephrased and re-ordered sections for clarity

Clarified how to run a vHive cluster in a kind container

---

examples/invoker/go.mod
examples/invoker/go.sum
function-images/tests/chained-function-eventing/go.mod
function-images/tests/chained-function-eventing/go.sum
utils/benchmarking/eventing/go.mod
utils/benchmarking/eventing/go.sum
utils/tracing/go/go.mod
utils/tracing/go/go.sum

includes #289, #317, #328, #329, #330, #332

bump dependencies

---

.github/workflows/invoker-test.yml
docs/benchmarking/adding_benchmarks.md

Add invoker-test.yml

---

scripts/github_runner/setup_runner_host.sh

Disable swap for self-hosted runners

---

.github/workflows/function-composition.yml
configs/docker-images/golang-builder/Dockerfile
configs/docker-images/runner/Dockerfile
configs/golang/Dockerfile
examples/invoker/.gitignore
function-images/tests/chained-function-eventing/Dockerfile
function-images/tests/chained-function-serving/Dockerfile

Add golang-builder and runner base images

---

bench_test.go
configs/knative_workloads/helloworld.yaml
configs/knative_workloads/helloworldSerial.yaml
configs/knative_workloads/pyaes.yaml
ctriface/bench_test.go
ctriface/iface.go
docs/local_registry.md
perf_bench_test.go
vhive.go
vhive_test.go

Switch workload container images from docker.io to ghcr.io

---

function-images/tests/stacking-training/driver/main.py

Dataset key must be taken from the get() return value.

Fixed bug in stacking benchmark

---

configs/.spellcheck.yml

Fixes spellcheck linter
Signed-off-by: Michal Baczun <s1743497@ed.ac.uk>

Fix for spellcheck linter

---

scripts/cloudlab/setup_node.sh

Signed-off-by: Michal Baczun <s1743497@ed.ac.uk>

Fixes stock-only flag in setup script

---

cri/Makefile
cri/cri_test.go
scripts/setup_system.sh

[hotfix] Remove skopeo dependency

---

functions.go

Added printing error in functions.go

---

docs/profiling.md

Run firecracker-containerd daemon when profiling

---

configs/knative_yamls/serving-core.yaml
configs/knative_yamls/serving-crds.yaml
configs/knative_yamls/serving-default-domain.yaml
configs/knative_yamls/serving-hpa.yaml
configs/knative_yamls/serving-post-install-jobs.yaml
configs/knative_yamls/serving-storage-version-migration.yaml
docs/developers_guide.md
scripts/install_stock.sh
scripts/setup_system.sh

Knative 1.4 upgrade

---

configs/knative_yamls/loader_serving_core.yaml
configs/knative_yamls/serving-core.yaml
scripts/cluster/create_multinode_cluster.sh
scripts/cluster/setup_master_node.sh

knative-serving placement moved to the master node which was previously empty.

Force knative-serving to master node

---

scripts/cluster/setup_master_node.sh

Changed the applied manifests to 1.4

---

docs/profiling.md

Correct the file name for install_pmutools.sh

---

docs/quickstart_guide.md

Fixes: https://github.com/vhive-serverless/vHive/issues/677

Fix firecracker-containerd start command

---

vhive.go

Closes #696
* Setup gVisor CRI at the same place as firecracker CRI.
* N/A
* N/A

Fix gVisor CRI setup in vHive orchestrator

---

docs/continuous_integration.md
scripts/github_runner/deploy_runners.go
scripts/github_runner/setup_bare_metal_runner.sh

Fixes to the CI runner deployer script to set up the vHive CI. 
* 
* 
* 

Fix the bare-metal CI

---

docs/logging.md

Create a page to document one method of collecting vHive logs and extract them to the local machine. This solution is proposed because `screen` sometimes interferes with logging.
* 
* 

Add documentation to collect and extract vHive logs

---

CHANGELOG.md
configs/calico/canal.yaml

Update Calico from v3.17.2 to v3.25.1

update calico to v3.25.1

---

CHANGELOG.md
configs/.wordlist.txt
configs/gpu/containerd_config.toml
configs/gpu/gpu-function.yaml
configs/gpu/gpu-pod.yaml
docs/developers_guide.md
function-images/hello_gpu/Dockerfile
function-images/hello_gpu/go.mod
function-images/hello_gpu/hello_gpu.go
function-images/hello_gpu/init.sh
scripts/gpu/setup_nvidia_gpu.sh
scripts/setup_system.sh

Add doc for using GPU in Knative
* adding scripts and document, in order to enable GPU in stock Knative which is installed using current scripts.
* 
* 

Add doc for using GPU in Knative

---

docs/contributing_to_vhive.md

Improved the descriptions in the "Rebasing on the Main Branch" and "Maintaining a Clean Main Branch & Avoiding Merge Commits" sections.
* Provided an example of the consequence of a messy merge without rebasing
* Included `git checkout your-branch` in the instructions on how to rebase on main
* Included clearer motivations behind maintaining a clean main branch and avoiding merge commits
* N/A
* N/A

Improved contributing_to_vhive.md: More detailed rationale and technique for Rebase & Merge

---

scripts/openyurt_deployer/main.go
scripts/openyurt_deployer/node/demo.go
scripts/openyurt_deployer/node/kube.go
scripts/openyurt_deployer/template/edgeNodePoolTemplate.go
scripts/openyurt_deployer/template/masterNodePoolTemplate.go
scripts/openyurt_deployer/template/yurtAppSetTemplate.go

add on demo.go
finding fixes for cleanNode()
* Demo.go will add template, to build Nodepool (for unitization function of OY) and label nodes, still required to add working image (please advise)
* added extra steps to `clean` function, still finding complete fix
* 
* 

adding features to easy_oy

---

CHANGELOG.md

Update changelog for a new v1.6 release of vHive

Update changelog for v1.6 release

---

configs/.wordlist.txt
docs/developers_guide.md
docs/logging.md
docs/quickstart_guide.md

Update all docs that were not updated previously after changes to setup procedure.

Update docs with new setup tool commands

---

.github/workflows/unit_tests.yml
profile/profiler.go

PMU tools can not work normally on github hosted runners
Add a self hosted runner and assign profile unit test running on that runner
* Change the implementation of detecting pmu tools and perf: stdout cannot be captured in self-hosted runners
* N/A
* N/A

change to utest runner

---

go.work
go.work.sum
scripts/github_runner/deploy_runners.go

Fix the build of deploy_runner tools after scripts Go module structure.

Fix build of deploy_runner and typos

---

configs/.wordlist.txt
docs/quickstart_guide.md
scripts/cluster/create_multinode_cluster.go

Fix some problems in quickstart:
* fix deployer path to function yamls
* fix creation of join k8s cluster command (print the whole command instead of getting the fields from yaml)

Update quickstart guide

---

.github/workflows/linters.yml

Bumped node.js version in GitHub runner workflow to 20

bump linter node.js version to 20

---

CHANGELOG.md

* Release vHive v1.7.1
* Modify the CHANGELOG
* N/A
* N/A

Release v1.7.1

---

.github/workflows/skip_build.yml
.github/workflows/skip_build_setup.yml
.github/workflows/skip_cri_tests.yml
.github/workflows/skip_firecracker_cri_tests.yml
.github/workflows/skip_gvisor_cri_tests.yml
.github/workflows/skip_integration_tests.yml
.github/workflows/skip_openyurt-unit-test.yml
.github/workflows/skip_stargz_tests.yml
.github/workflows/skip_unit_tests.yml

#984 
This PR is to fix this issue.
Referenced [Github doc](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks).

add workflows that skip github ckecks properly

---

CHANGELOG.md

Update the changelog before releasing new version

Prepare v1.8

---

docs/quickstart_guide.md

Fix the stargz image conversion commands to workaround #1137.

Modify image push command in quickstart guide
