vhive-serverless/vHive

scripts/install_go.sh
HTTPS authentication does not require a password
=> Remove ssh authentication in the setup script

.github/workflows/build.yml, .github/workflows/integration_tests.yml, .github/workflows/nightly_tests.yml, .github/workflows/tests.yml, .github/workflows/unit_tests.yml, Makefile, README.md, fccd-orchestrator_test.go, taps/taps_test.go
Split go.yml into build and tests. taps and misc now execute on github runners.
Removed "TestCreateRemoveExtra" taps test.
Signed-off-by: Shyam Jesalpura <s.jesalpura@gmail.com>
=> Split build and test CI config files

.github/workflows/build_function_images.yml, function-images/lr_serving/Dockerfile
Consecutive COPY commands in Dockerfile fail on github runners.
Added "DOCKER_BUILDKIT=1" Environment variable as a temporary fix.
Refer to the links below for more discussion on the issue:
https://github.com/moby/moby/issues/37965
https://github.community/t/attempting-to-build-docker-image-with-copy-from-on-actions/16715
https://stackoverflow.com/questions/51115856/docker-failed-to-export-image-failed-to-create-image-failed-to-get-layer
Signed-off-by: Shyam Jesalpura <s.jesalpura@gmail.com>
=> fix layer not found errors in function images build

functions.go
Increase startVM timeout value from 2 minutes to 5 minutes so that TestAllFunction passes on platforms with slow disks.
Signed-off-by: Dmitrii Ustiugov dmitrii.ustiugov@epfl.ch
=> Increase startVM timeout value

CHANGELOG.md, configs/.wordlist.txt
- Created a CI pipeline that runs CRI integration tests inside containers using kind.
- Added a developer image that runs a vHive k8s cluster in Docker, simplifying vHive development and debugging.
- Extended the developers guide on the modes of operation, performance analysis and vhive development environment inside containers.
- Added a slide deck of Dmitrii's talk at Amazon.
- Added a commit linter and a spell checker for `*.md` files.
- Use replace pragmas instead of Go modules.
- Bump Go version to 1.15 in CI.
- Deprecated Travis CI.
- Fixed the vHive cluster setup issue for clusters with >2 nodes issue.
=> vHive release v1.1

CHANGELOG.md, configs/.wordlist.txt, configs/storage/minio/deployment.yaml, configs/storage/minio/pv-claim.yaml, configs/storage/minio/pv.yaml, configs/storage/minio/service.yaml, docs/developers_guide.md
This PR introduces MinIO object storage deployment in a Kubernetes cluster.
Current setup:
* The storage class is `local-storage` that requires node affinity, hence a node name and an existing path on it.
* The MinIO service is exposed by a custom IP (i.e., ClusterIP publishing type) that is specified in `service.yaml`
The only type of storage that is supported is local storage (at least for now).
```bash
sudo mkdir -p <MINIO_PATH>
cd ./configs/storage/minio
MINIO_NODE_NAME=<MINIO_NODE_NAME> MINIO_PATH=<MINIO_PATH> envsubst < pv.yaml | kubectl apply -f -
kubectl apply -f pv-claim.yaml
kubectl apply -f deployment.yaml
kubectl apply -f service.yaml
```
An example of how the service can be accessed, using the [MinIO client](https://docs.min.io/docs/minio-client-quickstart-guide.html) …
=> MinIO server deployment in vHive (Kubernetes)

.github/workflows/cri_tests.yml, .github/workflows/unit_tests.yml, CHANGELOG.md, docs/developers_guide.md, docs/quickstart_guide.md, scripts/cloudlab/setup_node.sh, scripts/cluster/create_one_node_cluster.sh, scripts/cluster/setup_master_node.sh, scripts/cluster/setup_worker_kubelet.sh, scripts/github_runner/clean_cri_runner.sh, scripts/github_runner/setup_runner_host.sh, scripts/github_runner/start_runners.sh
- Add scripts to spawn a k8s cluster with stock containerd and knative for testing.
- Add stock containerd CRI test
- fixed kind path in start_runners.sh
- fixed kind build in setup_runner_host.sh
=> modify scripts to support stock knative cluster startup

.github/workflows/cri_tests.yml, CHANGELOG.md, configs/.wordlist.txt, docs/developers_guide.md, scripts/cluster/setup_master_node.sh, scripts/setup_zipkin.sh
Once the cluster is booted, run `istioctl dashboard zipkin` to start the [zipkin](https://zipkin.io/) dashboard.
- To monitor requests remotely, run `ssh -L 9411:127.0.0.1:9411 <Host_IP>` for port forwarding.
- Open your browser and enter [localhost:9411](http://localhost:9411) for the dashboard.
Screenshots:
=> add zipkin request tracing for Knative functions

configs/.wordlist.txt, docs/profiling.md, scripts/github_runner/Dockerfile.github_runner, scripts/github_runner/setup_runner.sh, scripts/github_runner/setup_runner_host.sh, scripts/install_pmutools.sh
=> moved pmutool installation to integ test dockerfile

.github/workflows/cri_tests.yml, CHANGELOG.md, configs/.wordlist.txt, cri/Makefile, scripts/cluster/setup_master_node.sh, scripts/setup_zipkin.sh
=> Add Knative eventing in default cluster setup

.github/workflows/cri_tests.yml, bin/firecracker, bin/jailer
- after rebasing the upf branch atop of upstream (v0.24)
- fixed sporadic errors in minio due to missing config file by manually setting KUBECONFIG variable
=> Updated the firecracker and jailer binaries to v0.24

CHANGELOG.md, perf_bench_test.go, profile/profiler.go, profile/profiler_test.go
- VMs can use all logical cores including the profiling one
- fix getting sibling of a processor error when SMT is off
- minor fix log level and argument check
Signed-off-by: NiuJ1ao <26167136+NiuJ1ao@users.noreply.github.com>
=> Fix binding policy

.github/workflows/cri_minio_test.yml, .github/workflows/cri_stock_containerd_test.yml, .github/workflows/cri_test.yml
=> Split cri workflow

.github/workflows/cri_test.yml, cri/Makefile, scripts/github_runner/start_runners.sh
```
Run echo $HOSTNAME
cri-test-github-runner-iccluster128-1-control-plane
691114828
```
The logs are stored on iccluster128 at /tmp/ctrd-logs/691114828/
=> make CRI test logs persistent

.github/workflows/build.yml, .github/workflows/build_docker_images.yml, .github/workflows/codeql-analysis.yml, .github/workflows/cri_minio_test.yml, .github/workflows/cri_stock_containerd_test.yml, .github/workflows/cri_test.yml, .github/workflows/integration_tests.yml, .github/workflows/linters.yml, .github/workflows/unit_tests.yml
We endorse the community's efforts to move to inclusive language usage. This PR renames the references to the master branch.
=> Rename master to main in our CI

.github/workflows/cri_minio_test.yml, CHANGELOG.md, configs/.wordlist.txt, cri/Makefile, docs/quickstart_guide.md, scripts/cloudlab/start_onenode_vhive_cluster.sh, scripts/cloudlab/start_vhive_cluster.sh, scripts/setup_system.sh
=> Add cluster restart script

.github/workflows/cri_minio_test.yml, .github/workflows/cri_stock_containerd_test.yml, .github/workflows/cri_test.yml, .github/workflows/nightly_tests.yml, configs/.wordlist.txt, cri/Makefile, docs/quickstart_guide.md, scripts/clean_fcctr.sh, scripts/cloudlab/start_onenode_vhive_cluster.sh, scripts/github_runner/clean_cri_runner.sh
* Added the CRI tests to nightly, checking modes w/ and w/o snapshots as well as REAP snapshots (`-upf`)
* Move stock Knative and MinIO tests to nightly, removing it from tests on push to a PR
* Refactored the script for (re)starting a vHive cluster
* Fixed the CRI cleaning script by removing the thinpool
* Adjusted the docs accordingly
=> Add CRI tests to nightly

.github/workflows/cri_minio_test.yml, .github/workflows/cri_stock_containerd_test.yml, .github/workflows/cri_test.yml, .github/workflows/nightly_tests.yml, README.md
* move duplicated env variable declarations to the workflow and job levels
* add job_id to nightly CRI logs to avoid parallel jobs overwrite each other's artifacts
=> Refactor CI env variables

perf_bench_test.go, scripts/github_runner/Dockerfile.github_runner, scripts/github_runner/setup_runner.sh, scripts/github_runner/start_runners.sh
changed the base image of integ test runner docker image to ubuntu 18.
To build the image:
```bash
git clone https://github.com/ease-lab/vhive
cd vhive
docker build -f ./scripts/github_runner/Dockerfile.github_runner ./ -t vhiveease/integ_test_runner:ubuntu18base
```
=> Fix integ runners

.github/workflows/cri_stock_containerd_test.yml, configs/knative_yamls/serving-default-domain.yaml, cri/cri_test.go, examples/deployer/client.go, function-images/tests/save_load_minio/scripts/run_minio_k8s.sh, scripts/cluster/setup_master_node.sh
This PR fixes #225:
- Replaced xip.io with nip.io as the DNS server for function name resolution. 
- Fixed the version of the net-istio manifest in the setup script (used to be v0.19.0).
=> Replaced xip.io to nip.io.

examples/deployer/client.go, examples/invoker/client.go
Rules:
- If a log.xxxF() ends with a simple (e.g., `%s`) formatter, use log.xxx() and remove the formatter instead.
- No space before and only one space after colons
- Consistent capitalization
=> Tidy logging messages in examples/{deployer,invoker}

scripts/install_go.sh, scripts/install_stock.sh, scripts/setup_system.sh
Make `setup_node.sh` quieter and more compliant
- Use "quiet" flag on commands that do not need to be verbose
- Prefer commands intended for scripting usage (e.g., `apt-get` over `apt`)
Edit: Just realised that I built this upon my previous work on updating the quickstart guide so this PR includes that commit too. Sorry! Not sure how to isolate this and that, but let me know if I can help.
=> Quieter setup_node.sh

configs/.wordlist.txt, docs/quickstart_guide.md
Improved the Quickstart Guide as discussed today. I have tested the multinode "Serverless (KNative) Cluster" setup extensively and the instructions work well.
@MBaczun Perhaps you would like to give your final feedback too?
=> Improved Quickstart Guide

scripts/cloudlab/setup_node.sh, scripts/disable_auto_updates.sh, scripts/install_stock.sh, scripts/setup_system.sh
- Silence `swapoff` errors
- Overwrite all without asking on unzipping `protoc`
- Try our best to kill/prevent conflicting apt processes running in background
- You may find this an overkill, I can revert it if you like but this should address the `E: Sub-process /usr/bin/dpkg returned an error code (1)` family of errors that @MBaczun and I (too) have experienced.
=> Improve setup_nodes.sh

scripts/install_stock.sh
Tested:
```
$ kn version
Version:      v20210531-local-5f68d61
Build Date:   2021-05-31 09:53:40
Git Revision: 5f68d61
Supported APIs:
* Serving
- serving.knative.dev/v1 (knative-serving v0.21.0)
* Eventing
- sources.knative.dev/v1alpha2 (knative-eventing v0.21.0)
- eventing.knative.dev/v1beta1 (knative-eventing v0.21.0)
```
`Version` field is sadly misleading; it is basically the build date... `Git Revision` (also the suffix of `Version`) is `5f68d61` and is equal to the [hash of v0.21.0](https://github.com/knative/client/releases/tag/v0.21.0). Rest is self-explanatory.
=> Pin Knative to v0.21.0

scripts/github_runner/Dockerfile.cri_dev_env
This resolves #279 where the docker image build was failing due to an upgrade of the container-commons version. Adding a custom repository to the sources list rather than using a hardcoded URL should also avoid this problem from happening again in the future.
=> Add skopeo custom repo to source list

CHANGELOG.md, configs/.wordlist.txt, ctriface/iface.go, ctriface/orch.go
Instead of redirecting workload container stderr and stdout to vhive stderr and stdout, it is now logged as:
```
time="2021-07-02T16:52:41.467607817Z" level=info msg="ERROR:root:testing logging2" vmID=15
```
Tested with [pyaes code](https://github.com/pogobanane/vhive/commit/cc27d35d4c125e197af9060a77a928e63c3bb0e6) / [image@docker hub](https://hub.docker.com/layers/154495195/pogobanane/vhive-workloads/slow_pyaes/images/sha256-cb84fe3df946c06be5b70c3b91475a27e07ea4389cc5931c6247ef1f8cf33578?context=explore).
=> wrap stdio of workload containers

cri/container_create.go
Insert error checking for container creation after calling stockRuntimeClient.CreateContainer
Not checking for this error lead to access on null pointer if the container creation failed.
Should fix #219
=> Added Error checking for container creation

.github/workflows/function-composition.yml, function-images/tests/video-analytics/Dockerfile, function-images/tests/video-analytics/decoder/decode.py, function-images/tests/video-analytics/docker-compose-inline.yml, function-images/tests/video-analytics/docker-compose-s3-tracing.yml, function-images/tests/video-analytics/docker-compose-s3.yml, function-images/tests/video-analytics/docker-compose-tracing.yml, function-images/tests/video-analytics/docker-compose-xdt.yml, function-images/tests/video-analytics/knative_yamls/inline/service-decoder.yaml, function-images/tests/video-analytics/knative_yamls/inline/service-recog.yaml, function-images/tests/video-analytics/knative_yamls/inline/service-streaming.yaml, function-images/tests/video-analytics/knative_yamls/s3/service-decoder.yaml, function-images/tests/video-analytics/knative_yamls/s3/service-recog.yaml, function-images/tests/video-analytics/knative_yamls/s3/service-streaming.yaml, function-images/tests/video-analytics/knative_yamls/xdt/service-decoder.yaml, function-images/tests/video-analytics/knative_yamls/xdt/service-recog.yaml, function-images/tests/video-analytics/knative_yamls/xdt/service-streaming.yaml, function-images/tests/video-analytics/video_streaming/reference/video.mp4
- add minimum scale to manifests to prevent scaling to 0.
- add optional env variable `CONCURRENT_RECOG` to infer frames in parallel
- #361
- add 1080p video sample video
=> Video bench min scale

.github/workflows/gvisor_cri_tests.yml, scripts/github_runner/start_bare-metal_runner.sh, scripts/github_runner/start_runners.sh
- Modified `scripts/github_runner/setup_runner_host.sh` to download multipass-packages when `multipass` flag is set.
- Modified `scripts/gihub_runner/start_runners.sh` to start gv-runners inside multipass VMs when `gvisor-cri` is set as runner_group. The script now depends on the new script `scripts/gihub_runner/start_bare-metal_runner.sh`.
- Added script `scripts/gihub_runner/start_bare-metal_runner.sh`, which starts a runner on the machine where the script is being run. This script follows the standard steps to start a GH-runner and has no dependencies on other scripts.
=> Scripts to start gvisor-cri-runners inside multipass-VMs

docs/quickstart_guide.md
The invoker and the deployer tools need to be built from their enclosing folders. This bug was introduced by our go.mod files optimizations. 
=> Fixed invoker & deployer in the quickstart guide

docs/knative/eventing.md, memory/manager/manager.go
Currently, the memory manager is not always unlocked when an error is returned.
=> Unlock memory manager upon returning error

scripts/install_pmutools.sh
Due to a [bug ](https://github.com/andikleen/pmu-tools/issues/408) in the upstream repo installing pmutools does not work.
This hotfix should solve the problem until the bug is fixed in the upstream.
=> Hotfix: #440. Error installing pmutools

.github/dependabot.yml
I wanted to bump the dependency for the Spellcheck GitHub Action to the latest version, when I noticed, that you already use Dependabot. So instead I am proposing adding the configuration to have Dependabot manage the GitHub Actions used in the repository
* The Dependabot configuration is scheduled to run weekly, which matches the other configurations. The implementation checks GitHub Actions, which are located in `.github/workflows/` so the configuration points to the directory of the `.github` repository.
* Dependabot is already configured
* None
=> Added Dependabot configuration for GitHub Actions

.github/workflows/gvisor_cri_tests.yml, scripts/github_runner/setup_runner_cri.sh, scripts/github_runner/setup_runner_host.sh, scripts/github_runner/start_bare-metal_runner.sh
fix CRI runners
- update `max_conntrack` limit for runner host. ref: [here](https://serverfault.com/questions/769978/sysctl-cannot-stat-proc-sys-net-ipv4-netfilter-ip-conntrack-max-no-such-file)
- fix actions-runner download link in [setup_runner_cri.sh](https://github.com/ease-lab/vhive/blob/main/scripts/github_runner/setup_runner_cri.sh) and [start_bare-metal_runner.sh](https://github.com/ease-lab/vhive/blob/main/scripts/github_runner/start_bare-metal_runner.sh).
- reorder instructions in [setup_runner_host.sh](https://github.com/ease-lab/vhive/blob/main/scripts/github_runner/setup_runner_host.sh)
=> fix cri runners

README.md, configs/.wordlist.txt
A full-day tutorial, co-located with the ASPLOS'22 conference, is going to take place in Lausanne, Switzerland on March 1. The tutorial will be in a hybrid format (both in-person and virtual) and will cover both the serverless cloud foundations and the vHive ecosystem and include several hands-on sessions. In this tutorial, the participants will learn how to analyze performance of commercial and open-source clouds as well as how to experiment and innovate across serverless stack using vHive. For more information, please visit the [tutorial webpage](https://ease-lab.github.io/vhive-asplos22/).
=> Serverless & vHive tutorial at ASPLOS'22 (announcement)

scripts/setup_system.sh
Fixes #473 .
* Adds universe repository in ubuntu
* Adds ca-certificates package to pull from opensuse repo
* N/A
* N/A
=> Fixes ubuntu desktop image error of package not found

cri/firecracker/service.go
This PR reintroduces the error check merged in #337. It seems to have disappeared between then and the most recent commit.
=> Reintroduce Error checking for container creation

configs/.linkcheck.json, docs/developers_guide.md
=> linkchecker: Added a workaround for links pointing to github repos

.github/workflows/cri_minio_test.yml, .github/workflows/nightly_tests.yml
Fixes failing nightly tests due to setup-go action's failure. Explained [here](https://github.com/actions/setup-go/issues/235#issuecomment-1127435881).
=> Do not set GOROOT in workflows

configs/knative_yamls/serving-core.yaml
To allow knative to pull docker.io images when run from behind the proxy while executing the deployer
* 
* 
=> allow docker.io images on systems behind proxy

docs/quickstart_guide.md
Added requirement and indications to set up ssh connections to cluster nodes to be of bash type, in order to avoid "Missing name for redirect" errors from running the commands from the guide.
* 
* 
=> Update: bash shell type requirement

.github/dependabot.yml
- Disabled tracking of some benchmarks (to be decomissioned in favor of vSwarm)
- Disable dependabot updates of patch versions
=> Optimized dependabot config

docs/developers_guide.md, docs/quickstart_guide.md
Add link to developer's guide in quick start guide for setting up one node stock only environment.
Add how to deploy functions to stock only environment.
=> Update quick start and developer's guide

README.md, configs/.linkcheck.json, go.mod, go.sum
- Removed Nate from the list of maintainers, as per his request.
- Updated Dmitrii's email
- Added links to the past tutorial at ASPLOS'22 and the recorded videos, the upcoming SESAME workshop at EuroSys'23
- Fixed other hyperlinks
=> Updated the maintainers, email, tutorial, workshop

function-images/lr_serving/requirements.txt
package name for sklearn is changed to scikit-learn 
* 
* 
=> fix the scikit-learn package name

cri/firecracker/coordinator.go, cri/firecracker/service.go, cri/gvisor/coordinator.go, cri/gvisor/service.go, cri/util.go, ctriface/iface.go
Any environment variables specified in the YAML specification are also passed on during image creation in `ctriface/iface.go`, so they are present in the instanced container.
=> Environment variables

function-images/lr_training_s3/requirements.txt
Similar to https://github.com/vhive-serverless/vHive/pull/678
package name for sklearn is changed to scikit-learn
* 
* 
=> fix the scikit-learn package name for lr_training

scripts/cluster/setup_master_node.sh
The metallb images have shifted the image repositories from docker.io to quay.io. This necessitates a change in the `kubectl apply -f` commands used in the vHive setup for deploying the metallb pods.
* The main change is in the image name for the metallb deployments. The original images were docker.io based, which have since changed to quay.io. Thus, I created new yaml files with the updated images, and then used these in the `kubectl apply -f` commands, replacing the original file.
* Images on quay.io (https://quay.io/repository/)
* The new version of metallb add ons is v0.9.6 on quay.io, instead of the original v0.9.4 on docker.io. I referred to the PR on Kubernetes (https://github.com/kubernetes/minikube/pull/16056) for getting this version.
*Simply specify none (N/A) if not …
=> Change in the image repository for metallb deployments

cri/Makefile, cri/cri_test.go
Closes #703
Current vHive CloudLab profile uses Ubuntu 20.04 image, which does not have
the skopeo package which is needed to pull image for local registry tests —
temporarily disable these tests until https://github.com/vhive-serverless/vHive/issues/709 is resolved.
N/A.
N/A.
=> Temporarily disable local registry tests from CRI tests

.github/workflows/build.yml, .github/workflows/build_docker_images.yml, .github/workflows/linters.yml
update action runner image to ubuntu-20.04 from 18.04 as github is deprecating 18.04
* 
* 
=> bump action runner image to ubuntu-20.04

scripts/install_stock.sh
Workaround for GPG key errors in the install script
* Sets the repo as trusted, meaning GPG keys do not get checked when installing from that repo.
* N/A
* N/A
=> GPG Key Workaround

examples/deployer/functions.json
rnn-serving is known to be unstable.
=> Remove rnn-serving from example functions

scripts/install_stock.sh
add google cloud public signing key
- change public signing key and apt repo script referring to [k8s official document](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management)
* 
* 
=> add google cloud public signing key

scripts/install_stock.sh
* k8s [opened a temporary URL](https://github.com/kubernetes/k8s.io/pull/4837) to handle inaccessibility of google live key repo
* this script will fall back to k8s gpg key if google live gpg key fails
* 
* 
=> fix google signing key issue by adding k8s mirror

configs/calico/canal.yaml
Fix networking in firecracker setup. Closes #781. Thanks [@smallpip](https://github.com/smallpip) for proposed solution.
* Ignore bridges interfaces created by vHive on worker nodes in calico configuration
* N/A
* N/A
=> Fix Firecracker setup networking

.github/workflows/cri_stock_containerd_test.yml, .github/workflows/firecracker_cri_tests.yml, .github/workflows/gvisor_cri_tests.yml, .github/workflows/integration_tests.yml, scripts/go.work
Add schedule event trigger to all the four self-hosted tests to make them run weekly
Add crons to the .github/ files
* 
* 
=> add schedule to run all self-hosted tests weekly

.github/workflows/unit_tests.yml, go.mod, networking/Makefile, networking/networkManager.go, networking/networkconfig.go, networking/networking.go, networking/networking_test.go
Closes #797
Part of #794
See #797 for details.
This PR introduces a new networking manager which implements the new network topology described in #797, but does not replace the existing tap manager, as it requires a patch to firecracker-containerd that adds a network namespace parameter to the CreateVM request.
Unit tests for the new networking manager are provided.
* N/A.
* N/A.
=> New network topology for firecracker VMs

.github/workflows/unit_tests.yml, ctriface/iface.go, ctriface/image/Makefile, ctriface/image/manager.go, ctriface/image/manager_test.go, ctriface/orch.go
Closes #799
Part of #794
* Introduced a new module `ctriface/image` and a new `ImageManager` object to manage container images.
* N/A.
* N/A.
=> Refactor container image management

.github/workflows/nightly_tests.yml, ctriface/Makefile, ctriface/iface_test.go, vhive.go, vhive_test.go
UPF feature for vanilla firecracker requires a separate integration effort (#807), so temporarily disable this feature and all tests for it.
* vHive and the vHive and orchestrator tests now exit with an error when UPF is enabled. 
* Tests using UPF are simply commented out.
* N/A.
* N/A.
=> Temporarily disable UPF feature and tests on `firecracker-v1.4.1-vhive-integration` branch

.github/workflows/unit_tests.yml, devmapper/Makefile, devmapper/deviceSnapshot.go, devmapper/devicemapper.go, devmapper/devicemapper_test.go
Closes #805
Part of #794
In the scope of #794, we will need to manage container snapshots backed by
the thin pool device mapper, so we need to introduce a separate module for
this.
* #800 must be merged first.
* N/A.
=> Add support for device mapper management

.github/workflows/unit_tests.yml, cri/firecracker/coordinator.go, ctriface/failing_test.go, ctriface/iface.go, ctriface/iface_test.go, ctriface/manual_cleanup_test.go, ctriface/orch.go, functions.go, snapshotting/Makefile, snapshotting/manager.go, snapshotting/manager_test.go, snapshotting/snapshot.go
Closes #802
Part of #794
Currently, VM snapshots are managed by the orchestrator via a table of idle function instances. With #794 snapshot management will become more complicated, and thus it requires refactoring into a separate module.
* N/A.
* N/A.
=> Refactor VM snapshot management

cri/firecracker/service.go, ctriface/iface.go, ctriface/orch.go, ctriface/orch_options.go, misc/misc_test.go, misc/vm_pool.go, taps/tapManager.go, taps/taps_test.go, taps/types.go
Currently, the host interface name is separated from the VM pool and tap
manager, and as a result, it needs to be passed to all VM pool methods.
This is inconvenient, and so encapsulate the host interface name into the
VM pool and tap manager.
Closes #810
Part of #794
* The host interface name is encapsulated into the VM pool and tap manager.
* N/A.
* N/A.
=> Encapsulate the host interface name into the VM pool and tap manager

functions.go
This will come in handy when the loaded instance will be a snapshot booted
VM rather than an offloaded one.
Goroutines capture variables by reference, so it is safer to make a copy
(i.e., a local variable) and pass the variable by value.
This will also come in handy when the function's VM ID can change when it
is loaded from a snapshot booted VM rather than an offloaded one.
This will come in handy when the function's VM ID will be assigned to
it after a VM for it is loaded from a snapshot (i.e., a new VM is created
rather than an offloaded one is reused). This logic follows the branch when
a snapshot is not available and a VM is booted from scratch.
* Replace manually created snapshots with snapshot manager in function pool;
* Propagate `StartVMResponse` from `Orch:LoadSnapshot` to …
=> Various enhancements to the vHive function pool

scripts/github_runner/deploy_runners.go, scripts/github_runner/setup_bare_metal_runner.sh
Add re-deployment steps to cri-runners. Now re-deployment will be run: 1. nightly 2. before every check
1. Add a new step in cri-tests: before every check, it will first re-deploy the runner
2. deployer.go now will add a cron task in 4:10am, try to re-deploy the runner nightly
3. In setup_bare_metal_runner.sh, rm the previously created service file so the re-deployment can be done without any error 
* 
* 
=> redeploy cri tests nightly

scripts/cluster/setup_master_node.go
On tutorial VMs setting up regularly fails due to timed out MetalLB services. In the end they are fine, just too long to be created.
* Increase timeout for deploying MetalLB cintroller.
* N/A
* N/A
=> Increase timeout for MetalLB setup

docs/quickstart_guide.md, scripts/install_go.sh
Install version of go configured in configs/setup/system.json by script. That will simplify the manual setup stage. Closes #851.
* Use jq to parse the config, install go by downloading the archive and decompressing it.
* N/A
* N/A
=> Install configurable version of go

configs/setup/vhive.json, scripts/cluster/setup_master_node.go, scripts/github_runner/Dockerfile.github_runner, scripts/setup_firecracker_containerd.sh
To support vanilla firecracker UPF features integration, update the current Firecracker kernel image link.
* Update firecracker kernel image download URL and config in scripts and GitHub runner
* https://github.com/firecracker-microvm/firecracker/blob/main/docs/getting-started.md#getting-a-rootfs-and-guest-kernel-image
* N/A
=> Update firecracker kernel image link

scripts/github_runner/README.md, scripts/github_runner/deploy_runners.go, scripts/github_runner/setup_profile_runner.sh
Add profile runner deployment script into the deployment tool
Add a bash script to setup the github runner
Modify the deploy_runner.go to add another self-hosted runner deploy option: `profile`
* 
* 
=> Add profile runner deployment scripts

scripts/cluster/create_multinode_cluster.go, scripts/cluster/setup_worker_kubelet.go, scripts/setup/setup.go
Fixes #931 **Error while deploying firecracker single-node deployment**
This issue is caused when migrating from bash script to go script. Did not change name properly.
https://github.com/vhive-serverless/vHive/blob/14f0b2d7ca9ab2a243063335c996e79d70349c5a/scripts/setup/setup.go#L91
---
Fixes #694 **required key GUEST_ADDR missing value**
This issue is caused by k8s version upgrade. After upgrade, they no longer support how we used to configure k8s before. This also fixes #899
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#the-kubelet-drop-in-file-for-systemd
https://github.com/kubernetes/release/issues/3392
=> Fix firecracker related issues

.github/workflows/integration_tests.yml, configs/knative_workloads/firecracker/helloworld.yaml, configs/knative_workloads/firecracker/helloworldSerial.yaml, configs/knative_workloads/firecracker/helloworld_local.yaml, configs/knative_workloads/firecracker/pyaes.yaml, configs/knative_workloads/gvisor/helloworld.yaml, configs/knative_workloads/gvisor/helloworldSerial.yaml, configs/knative_workloads/gvisor/pyaes.yaml, scripts/github_runner/conf.json, scripts/github_runner/deploy_runners.go, scripts/github_runner/setup_bare_metal_runner.sh, scripts/github_runner/setup_cri_test_env.sh
Fix #947 and other runner related issues
- Remove deprecated node setup script written in bash and migrate to go script
- Fix integration tests not working due to some missing packages and log name collision
- Make gVisor cri test to use proper yaml file: stub does not work with gVisor
- Let runner use specific branch to test runner upgrades
=> Fix runner issue

docs/quickstart_guide.md, scripts/cluster/setup_master_node.go
Add networking problem troubleshooting step: firewall configuration to accept traffic on 6443 port.
Add wait for node status to reduce the possibility of timeouts during metallb installation.
Both are problems encountered in #924.
* Wait for the state of the nodes after installation of CNI (calico in our case)
* N/A
* N/A
=> Add troubleshooting step and fix for metallb setup timeout

.github/workflows/build_setup.yml, .github/workflows/cri_minio_test.yml, .github/workflows/cri_stock_containerd_test.yml, .github/workflows/cri_tests.yml, .github/workflows/integration_tests.yml, .github/workflows/nightly_tests.yml, .github/workflows/openyurt-unit-test.yml, .github/workflows/stargz_tests.yml, .github/workflows/unit_tests.yml, configs/setup/system.json, docs/quickstart_guide.md
Downgrade GO version from 1.22.0 to 1.21.1
* Update `GoVersion` in ` configs/setup/system.json`
* Modify Github actions workflow
* NA
* NA
=> Downgrade Go to version 1.21.1

CHANGELOG.md, docs/power_manager.md, go.work, go.work.sum, power_manager/go.mod, power_manager/util.go, scripts/power_manager/power_config.yaml, scripts/power_manager/setup_power_manager.sh, scripts/power_manager/shared-profile.yaml, scripts/power_manager/shared-workload.yaml
This PR uses k8 Power Manager to tune CPU frequency and run experiments (workload sensitivity and internode scaling) to investigate how tuning frequencies can help to optimise power consumption in serverless computing
set up K8 power manager (power profiles, power workloads)
run the experiments using sleeping, spinning, auth, aes benchmarks from vSwarm
* 
* 
=> add power manager

scripts/cloudlab/start_onenode_vhive_cluster.go, scripts/cluster/create_one_node_cluster.go, scripts/setup.go
To better support the deployment and management of single-node Kubernetes clusters, I have created a new command `prepare_one_node_cluster`. Previously, the `create_one_node_cluster` command was responsible for both preparing the single-node environment and setting up the master node. Now, I have added a new command called `prepare_one_node_cluster`. With this new command, users can first prepare the single-node environment, and then manually run `setup_master_node` to set up the master node when needed. This increased flexibility enables users to selectively execute the relevant steps based on their specific needs.
First, I have split the `create_one_node_cluster` command into two parts: preparing the single-node environment and setting up the master node. Note that I have only divided …
=> create prepare_one_node_cluster command

.github/workflows/build.yml, .github/workflows/build_setup.yml, .github/workflows/cri_minio_test.yml, .github/workflows/cri_stock_containerd_test.yml, .github/workflows/cri_tests.yml, .github/workflows/integration_tests.yml, .github/workflows/nightly_tests.yml, .github/workflows/openyurt-unit-test.yml, .github/workflows/stargz_tests.yml, .github/workflows/unit_tests.yml, scripts/github_runner/clean_cri_runner.sh
We face gVisor runner failing all the time. 
There are two reasons:
Wrong endpoint caused whole error, and container not being cleaned up properly
```
W0424 11:02:04.475265  259894 cleanupnode.go:99] [reset] Failed to remove containers: [failed to stop running pod I0424: output: I0424 11:01:52.572194  260177 util_unix.go:103] "Using this endpoint is deprecated, please consider using full URL format" endpoint="/etc/vhive-cri/vhive-cri.sock" URL="unix:///etc/vhive-cri/vhive-cri.sock"
E0424 11:01:52.579298  260177 remote_runtime.go:222] "StopPodSandbox from runtime service failed" err="rpc error: code = NotFound desc = an error occurred when try to find sandbox \"I0424\": not found" podSandboxID="I0424"
time="2024-04-24T11:01:52Z" level=fatal msg="stopping the pod sandbox \"I0424\": rpc …
```
=> fix github runner gvisor failure and add gocache

cri/cri_test.go, scripts/cluster/create_multinode_cluster.go, scripts/cluster/setup_worker_kubelet.go, scripts/setup.go, scripts/utils/utils.go
Change the IPs of k8s nodes to the experimental subnet instead of the default (which is control in CloudLab).
* Add the argument for kubelet to use a specific IP from the internal subnet.
* N/A
* N/A
=> Change IPs from external to local

scripts/utils/utils.go
Change the bash command for getting node's private ip address
Now it would get the first ip address starting with 10.
Change bash command implementation to:
```
ip route | awk '{print $(NF)}' | awk '/^10\..*/ {print; exit}'
```
* N/A
* N/A
=> Fix GetNodeIP to get the first ip

configs/.wordlist.txt, docs/quickstart_guide.md, scripts/cloudlab/cloudlab-grow-rootfs.sh
Fixes #711. The setup script skipped the filesystem resizing step when reloading the node.
* Add logic to execute the filesystem resizing step even if the partition has the correct size already (which was the case on reload)
* Change the profile on CloudLab to the one managed by ntu-cloud project (only in docs)
* Changing CloudLab profile
* Edit CloudLab profile to use script from vHive repo instead of personal gist
* N/A
=> Add rootfs resizing script for CloudLab

cri/firecracker/coordinator.go, go.work.sum
The new version of golangci-linter found a long-standing error in the code.
* Fix error logging to be as expected
* N/A
* N/A
=> Fix golang linter error

scripts/cluster/setup_master_node.go
Misconfiguration of Calico was causing the inter-pod communication (including Knative-Istio communication) to be routed through control network if used on CloudLab clusters. This was causing high traffic on the control interface which is not advisable for CloudLab.
* Change the configuration of Calico to use k8s node IP which are set to experiment network.
* N/A
* N/A
=> Use node IP for inter pod routing

README.md, configs/.wordlist.txt
Update the maintainers list and remove the broken link to roadmap.
* N/A
* N/A
* N/A
=> Update maintainers in README.md

.github/workflows/build.yml, .github/workflows/build_docker_images.yml, .github/workflows/build_setup.yml, .github/workflows/linters.yml, .github/workflows/skip_build.yml, .github/workflows/skip_build_setup.yml, .github/workflows/skip_stargz_tests.yml, .github/workflows/skip_unit_tests.yml, .github/workflows/stargz_tests.yml, .github/workflows/unit_tests.yml, CHANGELOG.md, configs/.wordlist.txt, docs/quickstart_guide.md
Update the versions of Ubuntu in Github Runners due to Ubuntu 20.04 going deprecated.
* Update version in workflow
* Update profile on CloudLab to newer version of Ubuntu
* N/A
* N/A
=> Bump Ubuntu version in workflows

.github/workflows/cri_tests.yml, cri/firecracker/coordinator.go, cri/firecracker/coordinator_test.go
Ensure snapshots are initialized and committed using the same revision identifier to allow successful commit and future reuse.
Refer to #1087 for more details.
* Replaced the incorrect `fi.VmID` with `fi.Revision` in the call to `CommitSnapshot` on `orchCreateSnapshot`.
* Added test (`TestOrchCreateSnapshot`) to verify that the snapshot is correctly committed.
* N/A
* N/A
=> Fix snapshot commit

.github/workflows/unit_tests.yml, ctriface/Makefile, scripts/github_runner/gh-actions-disk-cleanup.sh
Some tests were failing due to insufficient disk space on the GitHub Actions runner. This commit adds a pre-test cleanup step that removes large, unused packages and SDKs to reclaim space and improve CI reliability.
This issue was discussed in this GH community [#25678](https://github.com/orgs/community/discussions/25678).
* N/A
* N/A
=> Improve CI reliability

ctriface/Makefile, ctriface/manual_cleanup_test.go, scripts/stargz/setup_stargz.go
The unit tests for the Firecracker-containerd interface using the stargz snapshotter were too flaky. It's better to run them in a more controlled way. By running them manually, we can clean and restart Firecracker, making the tests less flaky.
- Changed tests in `ctriface/manual_cleanup_test.go` to allow using stargz snapshotter, by using the same parameters used in `ctriface/iface_test.go`.
N/A
N/A
=> Convert stargz tests to manual tests
